### ISSUE TITLE
Hi i'm having problem with the compilation.

### ISSUE THREAD

**Issue by RealAquilus** [kiyakkoray/Swarm2D#1]
If i compile with SharpDevelop i get an error that is: The OutputPath property is not set for project 'Swarm2D.SpriteEditor.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='AnyCPU'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform. - C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets:617,5.
If i try to compile with Visual Studio 2013 Update 5 i get no error but no scene.exe were created and i can't start the engine. please help me!

**Comment by kiyakkoray** [comment]
Hello,
Sorry for my delayed reply. I can say that this project is still in early stages. I'm using Visual Studio 2013 to compile it. 2015 would probably work too. (Don't have idea about the SharpDevelop). In order to run the engine you also need some resource files which i plan to add them to projects web site with the example games soon.

Thank you for your interest :)
